let token=localStorage.hb_token||"", user=JSON.parse(localStorage.hb_user||"null"), cart=JSON.parse(localStorage.hb_cart||"[]");
const $=x=>document.getElementById(x), money=n=>new Intl.NumberFormat("fr-FR").format(n)+" FCFA";
async function api(path,opt={}){opt.headers={"Content-Type":"application/json",...(opt.headers||{})};if(token)opt.headers.Authorization="Bearer "+token;const r=await fetch("/api"+path,opt);const d=await r.json();if(!r.ok)throw Error(d.error||"Erreur");return d}
function toast(m){let t=$("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
async function init(){try{const [cats,shops,products]=await Promise.all([api("/categories"),api("/shops"),api("/products")]);renderCats(cats);renderShops(shops);renderProducts(products);renderFilters(cats)}catch(e){toast(e.message)}renderCart()}
function renderCats(a){$("cats").innerHTML=(a.length?a.map(x=>`<div class="cat" onclick="loadProducts('${x.category}')"><div class="ico">🛍️</div><h3>${x.category}</h3><p>${x.count} produit(s)</p></div>`):[]).join("")||"<div class=\"cat\"><div class=\"ico\">🛍️</div><h3>Marketplace</h3></div>"}
function renderShops(a){$("shopsGrid").innerHTML=a.map(s=>`<div class="shop" onclick="shop(${s.id})"><div><b>${s.name}</b><small>${s.category||"Boutique"}</small><p style="font-size:8px;color:#777">${s.products} produit(s)</p></div></div>`).join("")}
function renderFilters(c){$("filters").innerHTML=["Tous",...c.map(x=>x.category)].map(x=>`<button class="filter ${x==="Tous"?"active":""}" onclick="loadProducts('${x}')">${x}</button>`).join("")}
function renderProducts(a){$("productsGrid").innerHTML=a.length?a.map(p=>`<article class="card" onclick="product(${p.id})"><div class="pic">${p.image||"🛍️"}${p.stock<5?'<span class="badge">DERNIÈRES PIÈCES</span>':""}</div><div class="info"><div class="store">${p.shop_name}</div><h3>${p.name}</h3><div class="stars">★★★★★</div><div class="price">${money(p.price)}</div><button class="add" onclick="event.stopPropagation();add(${p.id})">AJOUTER AU PANIER</button></div></article>`).join(""):"<p>Aucun produit.</p>"}
async function loadProducts(cat="Tous"){let a=await api("/products"+(cat!=="Tous"?`?category=${encodeURIComponent(cat)}`:""));renderProducts(a);$("products").scrollIntoView({behavior:"smooth"})}
async function sales(){let a=(await api("/products")).filter(p=>p.price<70000);renderProducts(a);$("products").scrollIntoView({behavior:"smooth"})}
async function product(id){let p=(await api("/products")).find(x=>x.id===id);$("modalContent").innerHTML=`<p class="eyebrow">${p.shop_name}</p><h2>${p.name}</h2><div style="font-size:120px;text-align:center">${p.image||"🛍️"}</div><p>${p.description||""}</p><h2 style="color:#d8a72a">${money(p.price)}</h2><p>Stock : ${p.stock}</p><button class="gold full" onclick="add(${p.id});closeAll()">Ajouter au panier</button>`;$("modal").classList.add("show")}
function add(id){let x=cart.find(i=>i.id===id);x?x.q++:cart.push({id,q:1});localStorage.hb_cart=JSON.stringify(cart);renderCart();toast("Produit ajouté au panier")}
function renderCart(){$("count").textContent=cart.reduce((a,x)=>a+x.q,0);$("cartItems").innerHTML=cart.length?cart.map(x=>{let p=PRODUCT_CACHE.find(p=>p.id===x.id)||null;return p?`<div class="cartrow"><div class="thumb">${p.image||"🛍️"}</div><div><h4>${p.name}</h4><small>${money(p.price)}</small><div class="qty"><button onclick="change(${p.id},-1)">−</button>${x.q}<button onclick="change(${p.id},1)">+</button></div></div><button class="x" style="float:none;font-size:19px" onclick="removeItem(${p.id})">×</button></div>`:""}).join(""):"<p style='color:#777'>Votre panier est vide.</p>";$("total").textContent=money(cart.reduce((a,x)=>a+x.q*(PRODUCT_CACHE.find(p=>p.id===x.id)?.price||0),0))}
let PRODUCT_CACHE=[];
async function cache(){PRODUCT_CACHE=await api("/products");renderCart()}
function change(id,n){let x=cart.find(i=>i.id===id);x.q+=n;if(x.q<1)cart=cart.filter(i=>i.id!==id);localStorage.hb_cart=JSON.stringify(cart);renderCart()}
function removeItem(id){cart=cart.filter(i=>i.id!==id);localStorage.hb_cart=JSON.stringify(cart);renderCart()}
function openCart(){$("drawer").classList.add("open");$("shade").classList.add("show")}
function closeCart(){$("drawer").classList.remove("open");$("shade").classList.remove("show")}
function closeAll(){closeCart();document.querySelectorAll(".modal").forEach(m=>m.classList.remove("show"))}
function loginForm(){ $("modalContent").innerHTML=`<p class="eyebrow">ESPACE CLIENT</p><h2>Connexion</h2><form class="form" onsubmit="login(event)"><input id="email" type="email" required placeholder="Email"><input id="password" type="password" required placeholder="Mot de passe"><button class="gold">Se connecter</button></form><p style="font-size:10px;color:#777">Pas de compte ? <button class="outline" onclick="registerForm()">Créer un compte</button></p>`;$("modal").classList.add("show")}
function registerForm(){$("modalContent").innerHTML=`<p class="eyebrow">HIGHNESS BIGMARKET</p><h2>Créer mon compte</h2><form class="form" onsubmit="register(event)"><input id="name" required placeholder="Nom complet"><input id="email" required type="email" placeholder="Email"><input id="phone" placeholder="Téléphone"><input id="password" required type="password" placeholder="Mot de passe"><button class="gold">Créer le compte</button></form>`}
async function login(e){e.preventDefault();try{let d=await api("/auth/login",{method:"POST",body:JSON.stringify({email:$("email").value,password:$("password").value})});setSession(d);closeAll();dashboard()}catch(x){toast(x.message)}}
async function register(e){e.preventDefault();try{let d=await api("/auth/register",{method:"POST",body:JSON.stringify({name:$("name").value,email:$("email").value,phone:$("phone").value,password:$("password").value})});setSession(d);closeAll();dashboard()}catch(x){toast(x.message)}}
function setSession(d){token=d.token;user=d.user;localStorage.hb_token=token;localStorage.hb_user=JSON.stringify(user)}
function sellerModal(){if(!user)return loginForm();$("modalContent").innerHTML=`<p class="eyebrow">ESPACE PRESTATAIRE</p><h2>Créer ma boutique</h2><form class="form" onsubmit="applySeller(event)"><input id="shopname" required placeholder="Nom de la boutique"><input id="shopcat" placeholder="Catégorie"><textarea id="shopdesc" placeholder="Présentation de la boutique"></textarea><button class="gold">Envoyer la demande</button></form>`;$("modal").classList.add("show")}
async function applySeller(e){e.preventDefault();try{await api("/seller/apply",{method:"POST",body:JSON.stringify({name:$("shopname").value,category:$("shopcat").value,description:$("shopdesc").value})});closeAll();toast("Demande envoyée à l'administration.")}catch(x){toast(x.message)}}
async function dashboard(){document.querySelector("main").innerHTML=`<section class="section"><div class="dash" id="dash"></div></section>`;if(user.role==="admin")return adminDash();if(user.role==="seller")return sellerDash();return clientDash()}
async function clientDash(){let orders=await api("/orders");$("dash").innerHTML=`<div class="row"><div><p class="eyebrow">ESPACE CLIENT</p><h2>Bonjour ${user.name}</h2></div><button class="outline" onclick="home()">Retour au marketplace</button></div><div class="stats"><div class="stat"><small>Commandes</small><b>${orders.length}</b></div><div class="stat"><small>Panier</small><b>${cart.length}</b></div><div class="stat"><small>Compte</small><b>ACTIF</b></div><div class="stat"><small>Notifications</small><b>—</b></div></div><div class="panel"><h3>Mes commandes</h3>${orders.length?`<table class="table"><tr><th>#</th><th>Total</th><th>Paiement</th><th>Statut</th></tr>${orders.map(o=>`<tr><td>#${o.id}</td><td>${money(o.total)}</td><td>${o.payment_status}</td><td>${o.status}</td></tr>`).join("")}</table>`:"<p style='color:#777'>Aucune commande pour le moment.</p>"}</div>`}
async function sellerDash(){let d=await api("/seller/dashboard");$("dash").innerHTML=`<div class="row"><div><p class="eyebrow">ESPACE PRESTATAIRE</p><h2>${d.shop?.name||"Ma boutique"}</h2></div><button class="outline" onclick="home()">Marketplace</button></div><div class="stats"><div class="stat"><small>Ventes brutes</small><b>${money(d.stats.gross)}</b></div><div class="stat"><small>Commandes</small><b>${d.stats.orders}</b></div><div class="stat"><small>Produits</small><b>${d.products.length}</b></div><div class="stat"><small>Statut</small><b>${d.shop?.status||"—"}</b></div></div><div class="panel"><h3>Ajouter un produit</h3><form class="form" onsubmit="addProduct(event)"><input id="pn" required placeholder="Nom"><input id="pp" required type="number" placeholder="Prix FCFA"><input id="ps" required type="number" placeholder="Stock"><input id="pc" placeholder="Catégorie"><input id="pi" placeholder="Emoji / URL image"><textarea id="pd" placeholder="Description"></textarea><button class="gold">Publier le produit</button></form></div><div class="panel"><h3>Mes produits</h3><table class="table"><tr><th>Produit</th><th>Prix</th><th>Stock</th></tr>${d.products.map(p=>`<tr><td>${p.name}</td><td>${money(p.price)}</td><td>${p.stock}</td></tr>`).join("")}</table></div>`}
async function addProduct(e){e.preventDefault();try{await api("/seller/products",{method:"POST",body:JSON.stringify({name:$("pn").value,price:$("pp").value,stock:$("ps").value,category:$("pc").value,image:$("pi").value,description:$("pd").value})});toast("Produit publié");sellerDash()}catch(x){toast(x.message)}}
async function adminDash(){let d=await api("/admin/dashboard");$("dash").innerHTML=`<div class="row"><div><p class="eyebrow">ADMINISTRATION</p><h2>HIGHNESS BIGMARKET</h2></div><button class="outline" onclick="home()">Marketplace</button></div><div class="stats">${Object.entries({Utilisateurs:d.stats.users,Boutiques:d.stats.shops,"En attente":d.stats.pendingShops,Produits:d.stats.products,Commandes:d.stats.orders,"Chiffre d'affaires":money(d.stats.revenue),Commissions:money(d.stats.commissions)}).map(([k,v])=>`<div class="stat"><small>${k}</small><b>${v}</b></div>`).join("")}</div><div class="panel"><h3>Boutiques à valider</h3>${d.pending.length?d.pending.map(s=>`<div style="padding:12px;border-bottom:1px solid #222"><b>${s.name}</b> — ${s.owner_name} — ${s.category}<br><button class="gold" onclick="approve(${s.id},'approved')">Approuver</button> <button class="outline" onclick="approve(${s.id},'rejected')">Refuser</button></div>`).join(""):"<p style='color:#777'>Aucune demande en attente.</p>"}</div><div class="panel"><h3>Commandes récentes</h3><table class="table"><tr><th>#</th><th>Total</th><th>Paiement</th><th>Statut</th></tr>${d.recentOrders.map(o=>`<tr><td>#${o.id}</td><td>${money(o.total)}</td><td>${o.payment_status}</td><td><select onchange="orderStatus(${o.id},this.value)">${["pending","confirmed","processing","shipped","delivered","cancelled"].map(x=>`<option ${x===o.status?"selected":""}>${x}</option>`).join("")}</select></td></tr>`).join("")}</table></div>`}
async function approve(id,status){await api("/admin/shops/"+id,{method:"PATCH",body:JSON.stringify({status})});adminDash()}
async function orderStatus(id,status){await api("/admin/orders/"+id,{method:"PATCH",body:JSON.stringify({status})});toast("Statut mis à jour")}
async function checkout(){if(!cart.length)return toast("Panier vide");if(!user)return loginForm();$("modalContent").innerHTML=`<p class="eyebrow">CHECKOUT</p><h2>Finaliser ma commande</h2><form class="form" onsubmit="placeOrder(event)"><input id="dn" value="${user.name||""}" required placeholder="Nom"><input id="dp" value="${user.phone||""}" required placeholder="Téléphone"><input id="dc" required placeholder="Ville"><input id="da" required placeholder="Adresse"><select id="pm"><option value="mobile_money">Mobile Money</option><option value="card">Carte bancaire</option></select><button class="gold">Payer et commander</button></form><small style="color:#777">En mode démonstration, aucun argent réel n'est débité.</small>`;$("modal").classList.add("show")}
async function placeOrder(e){e.preventDefault();try{let d=await api("/orders",{method:"POST",body:JSON.stringify({items:cart.map(x=>({productId:x.id,quantity:x.q})),delivery:{name:$("dn").value,phone:$("dp").value,city:$("dc").value,address:$("da").value},paymentMethod:$("pm").value})});cart=[];localStorage.hb_cart="[]";renderCart();closeAll();toast("Commande #"+d.order.id+" créée");dashboard()}catch(x){toast(x.message)}}
function home(){location.reload()}function shop(id){location.href="#shops";toast("Boutique #"+id+" — page boutique à ouvrir depuis l'API")}
$("account").onclick=()=>user?dashboard():loginForm();$("cart").onclick=openCart;$("search").onsubmit=async e=>{e.preventDefault();let q=$("q").value;renderProducts(await api("/products?q="+encodeURIComponent(q)));location.hash="products"};init().then(cache);